
spring.datasource.url=jdbc:oracle:thin:@//oracle.fiap.com.br:1521/ORCL
spring.datasource.username=RM_AQUI
spring.datasource.password=SENHA_AQUI
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


api.security.token.secret=St3ll4rG3ar-Gl0b4lS0lut10n-Fi4p-2026!@#


spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always